# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31562dde8c4121861e1248f0cb3abdccd843a1a4c711c52d051c436b6ba23a3fe0dd06476fa72b0f5818a11037d2d25d90fe499483e0db49dce74a33a7b9b670

test:
  secret_key_base: 15d04073de7fb2b945770beb1419d217e92601399a6c1675741afaed130fe30c776471d342c3807830cd711b65ecb5872607447a24bcf3d6bbdf20c955fba0b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
